package project_euler;

public class second_problem {

	public static void main(String[] args) {
		
/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */
	
	int n1=1,n2=0,n3=0,sum=0;
	do {
			n3=n1+n2;
			n2=n1;
			n1=n3;
			//System.out.println(n3);
			
			if(n3%2==0) {
				sum+=n3;
			}	
		}
	while(n3 < 4000000);
	
	System.out.println(sum);
	}

}
